=== jovanrt2916/ist-provera-znanja/magacin.dtd
<!ELEMENT Magacin (Artikal)+>

<!ELEMENT Artikal (Naziv,DatumIzrade,Cena,KompanijaProdavca,(EmailProdavca)+)>

<!ELEMENT Naziv (#PCDATA)>
<!ATTLIST Naziv sifra_artikla ID>

<!ELEMENT DatumIzrade (Dan,Mesec,Godina)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>

<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena tip (dinar|euro) "dinar">

<!ELEMENT KompanijaProdavca (ImeKompanije, (AdresaKompanije)+)>
<!ELEMENT ImeKompanije (#PCDATA)>
<!ELEMENT AdresaKompanije (#PCDATA)>

<!ELEMENT EmailProdavca (#PCDATA)>
<!ATTLIST EmailProdavca tip (privatni|sluzbeni) #REQUIRED>

=== jovanrt2916/ist-provera-znanja/magacin.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE Adresar SYSTEM "magacin.dtd">
<Magacin>
    <Artikal>
        <Naziv sifra_artikla="321123">
            Mleko
        </Naziv>

        <DatumIzrade>
            <Dan>2</Dan>
            <Mesec>5</Mesec>
            <Godina>2020</Godina>
        </DatumIzrade>

        <Cena>95</Cena>

        <KompanijaProdavca>
            <ImeKompanije>Imlek D.O.O</ImeKompanije>
            <AdresaKompanije>Neznanog Junaka bb</AdresaKompanije>
        </KompanijaProdavca>

        <EmailProdavca tip="sluzbeni">support@imlek.rs</EmailProdavca>
    </Artikal>

    <Artikal>
        <Naziv sifra_artikla="800880">
            Kafa
        </Naziv>

        <DatumIzrade>
            <Dan>17</Dan>
            <Mesec>3</Mesec>
            <Godina>2020</Godina>
        </DatumIzrade>

        <Cena tip="euro">1.85</Cena>

        <KompanijaProdavca>
            <ImeKompanije>Bonito</ImeKompanije>
            <AdresaKompanije>Omladinskih Brigada 32</AdresaKompanije>
        </KompanijaProdavca>

        <EmailProdavca tip="privatni">bonito_ceo@gmail.com</EmailProdavca>
    </Artikal>
</Magacin>
